---
- name: Configure Servers
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and upgrade packages (for Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install essential packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - git
        - python3

    - name: Ensure Nginx service is enabled and started
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure firewall to allow SSH (port 22) and HTTP (port 80)
      ufw:
        rule: "{{ item }}"
        state: present
      with_items:
        - "allow ssh"
        - "allow http"

    # Add more tasks as needed for specific server configuration
